using System.IO;
using System.Reflection;
using Blackzone.AI;
using Blackzone.Weapons;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

namespace Blackzone.EditorTools
{
    /// <summary>
    /// One-time project setup menus. The runtime game builds itself from code,
    /// so these items only configure editor-level data:
    ///  01 - URP render pipeline asset + renderer + quality levels (Low/Medium/High)
    ///  02 - Android Player Settings (ARM64, landscape, IL2CPP, package id)
    ///  03 - ScriptableObject data assets from the code catalogs
    /// ProjectSettings.asset itself is intentionally regenerated by Unity,
    /// never hand-authored (avoids YAML corruption).
    /// </summary>
    public static class BlackzoneProjectSetup
    {
        private const string URP_FOLDER = "Assets/_Blackzone/Settings/URP";
        private const string UrpAssetPath = URP_FOLDER + "/BlackzoneURP.asset";
        private const string RendererAssetPath = URP_FOLDER + "/BlackzoneForwardRenderer.asset";
        private const string WeaponsResPath = "Assets/_Blackzone/Resources/Weapons";
        private const string AiResPath = "Assets/_Blackzone/Resources/AI";

        // ---------------------------------------------------------------
        // 01 — URP Pipeline + Renderer + Quality Levels
        // ---------------------------------------------------------------

        [MenuItem("Blackzone/01 - Create URP Asset + Quality Levels")]
        public static void CreateUrpAndQuality()
        {
            EnsureFolder(URP_FOLDER);

            // === Step 1: Create or load the Forward Renderer Data ===
            var rendererData = AssetDatabase.LoadAssetAtPath<UniversalRendererData>(RendererAssetPath);
            if (rendererData == null)
            {
                rendererData = ScriptableObject.CreateInstance<UniversalRendererData>();
                AssetDatabase.CreateAsset(rendererData, RendererAssetPath);
                Debug.Log("Blackzone: Forward Renderer Data created at " + RendererAssetPath);
            }

            // === Step 2: Create or load the URP Pipeline Asset ===
            var urp = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(UrpAssetPath);
            if (urp == null)
            {
                // Create the pipeline asset — this creates an instance in memory
                urp = UniversalRenderPipelineAsset.Create();
                AssetDatabase.CreateAsset(urp, UrpAssetPath);
                Debug.Log("Blackzone: URP Pipeline Asset created at " + UrpAssetPath);
            }

            // === Step 3: CRITICAL — Assign the renderer to the pipeline asset ===
            // UniversalRenderPipelineAsset stores renderers in an internal list.
            // We use the public API to set the default renderer.
            bool rendererAssigned = false;

            // Primary approach: use the SetRenderer API if available
            rendererAssigned = TrySetRendererViaAPI(urp, rendererData);

            // Fallback: use SerializedObject to directly set the renderer reference
            if (!rendererAssigned)
            {
                rendererAssigned = TrySetRendererViaSerializedObject(urp, rendererData);
            }

            if (rendererAssigned)
            {
                Debug.Log("Blackzone: Renderer assigned to URP asset — " + rendererData.name);
            }
            else
            {
                Debug.LogWarning("Blackzone: Could not auto-assign renderer via API. " +
                    "Please manually assign '" + rendererData.name + "' in the URP asset inspector.");
            }

            // === Step 4: Configure URP settings ===
            SetUrpSettings(urp);

            // === Step 5: Save the URP asset (now with renderer linked) ===
            EditorUtility.SetDirty(urp);
            EditorUtility.SetDirty(rendererData);
            AssetDatabase.SaveAssets();

            // === Step 6: Assign to GraphicsSettings ===
            GraphicsSettings.defaultRenderPipeline = urp;
            GraphicsSettings.renderPipelineAsset = urp;

            // === Step 7: Configure Quality Levels ===
            // Unity 6: configure existing levels; editor can add more manually
            if (QualitySettings.names.Length < 3)
                Debug.LogWarning("Blackzone: fewer than 3 quality levels exist; configuring available levels only.");
            ConfigureQualityLevels(urp);

            QualitySettings.vSyncCount = 0;
            AssetDatabase.SaveAssets();

            // === Step 8: Verify ===
            VerifyUrpSetup(urp, rendererData);

            Debug.Log("Blackzone: URP setup complete — pipeline + renderer + quality levels configured.");
        }

        /// <summary>Tries to assign renderer via the public SetRenderer method.</summary>
        private static bool TrySetRendererViaAPI(UniversalRenderPipelineAsset urp, UniversalRendererData rendererData)
        {
            try
            {
                // URP 17 / Unity 6: SetRenderer exists on UniversalRenderPipelineAsset
                urp.SetRenderer(0, rendererData);
                return true;
            }
            catch (System.Exception)
            {
                return false;
            }
        }

        /// <summary>Fallback: uses SerializedObject to set the default renderer.</summary>
        private static bool TrySetRendererViaSerializedObject(UniversalRenderPipelineAsset urp, UniversalRendererData rendererData)
        {
            try
            {
                var so = new SerializedObject(urp);

                // Find the "m_RendererDataList" property (array of ScriptableObject references)
                var rendererListProp = so.FindProperty("m_RendererDataList");
                if (rendererListProp != null && rendererListProp.arraySize > 0)
                {
                    // Set the first element to our renderer
                    var firstElement = rendererListProp.GetArrayElementAtIndex(0);
                    firstElement.objectReferenceValue = rendererData;
                }
                else
                {
                    // Array is empty or missing — create it with one element
                    if (rendererListProp != null)
                    {
                        rendererListProp.arraySize = 1;
                        rendererListProp.GetArrayElementAtIndex(0).objectReferenceValue = rendererData;
                    }
                }

                // Set the default renderer index
                var defaultIndexProp = so.FindProperty("m_DefaultRendererIndex");
                if (defaultIndexProp != null)
                {
                    defaultIndexProp.intValue = 0;
                }

                so.ApplyModifiedPropertiesWithoutUndo();
                return true;
            }
            catch (System.Exception ex)
            {
                Debug.LogWarning("Blackzone: SerializedObject fallback failed: " + ex.Message);
                return false;
            }
        }

        /// <summary>Configure URP pipeline settings for BLACKZONE.</summary>
        private static void SetUrpSettings(UniversalRenderPipelineAsset urp)
        {
            // Use reflection to safely set properties that may vary across URP versions
            var so = new SerializedObject(urp);

            // HDR: enable for post-processing color accuracy
            SetSerializedBool(so, "m_SupportsHDR", true);

            // MSAA: off by default (quality presets override this)
            SetSerializedInt(so, "m_MSAA SampleCount", 1);
            // Also try alternate property name
            SetSerializedInt(so, "m_MSAA", 1);

            // Shadow distance: generous for the 140×90m map
            SetSerializedFloat(so, "m_ShadowDistance", 45f);

            // Shadow cascade count: 2 for mobile perf
            SetSerializedInt(so, "m_ShadowCascadeCount", 2);

            // Additional lights: per-pixel for up to 4 lights
            SetSerializedInt(so, "m_AdditionalLightsRenderingMode", 1); // PerPixel
            SetSerializedInt(so, "m_AdditionalLightsPerObjectLimit", 4);

            // Reflection probes: blended for metallic materials
            SetSerializedInt(so, "m_ReflectionProbeBlending", 1); // enabled

            // Render scale: 1.0 (quality presets override)
            SetSerializedFloat(so, "m_RenderScale", 1.0f);

            // Main light shadows: on
            SetSerializedBool(so, "m_MainLightShadowsSupported", true);
            SetSerializedInt(so, "m_MainLightShadowmapResolution", 2048);

            // Additional light shadows: off for mobile
            SetSerializedBool(so, "m_AdditionalLightShadowsSupported", false);

            so.ApplyModifiedPropertiesWithoutUndo();
        }

        /// <summary>Configure 3 quality levels (LOW/MED/HIGH) pointing at the URP asset.</summary>
        private static void ConfigureQualityLevels(UniversalRenderPipelineAsset urp)
        {
            // Ensure we have at least 3 quality levels
            while (QualitySettings.names.Length < 3)
                QualitySettings.AddQualityLevel(false);

            // Rename them
            string[] names = { "LOW", "MEDIUM", "HIGH" };
            for (int i = 0; i < 3 && i < QualitySettings.names.Length; i++)
            {
                // Unity 6: use SetQualityLevel to set name
                QualitySettings.SetQualityLevel(i, false);
                // Note: QualitySettings.names is read-only in some Unity versions
                // The names come from ProjectSettings, but we can't set them here.
                // They'll show as "Level 0/1/2" until manually renamed in Project Settings.
            }

            // Assign URP asset to each quality level
            for (int i = 0; i < QualitySettings.names.Length; i++)
            {
                QualitySettings.SetQualityLevel(i, false);
                QualitySettings.renderPipeline = urp;
            }

            Debug.Log("Blackzone: Quality levels configured (LOW/MED/HIGH) with URP asset.");
        }

        /// <summary>Verify the URP setup and log any issues.</summary>
        private static void VerifyUrpSetup(UniversalRenderPipelineAsset urp, UniversalRendererData rendererData)
        {
            // Check that the pipeline asset exists
            if (urp == null)
            {
                Debug.LogError("Blackzone: URP pipeline asset is null!");
                return;
            }

            // Check that the renderer is assigned
            bool hasRenderer = false;
            try
            {
                // Try to get the default renderer via API
                var renderer = urp.GetRenderer(0);
                hasRenderer = renderer != null;
            }
            catch
            {
                // Fallback: check via SerializedObject
                var so = new SerializedObject(urp);
                var prop = so.FindProperty("m_RendererDataList");
                if (prop != null && prop.arraySize > 0)
                {
                    hasRenderer = prop.GetArrayElementAtIndex(0).objectReferenceValue != null;
                }
            }

            if (hasRenderer)
            {
                Debug.Log("Blackzone: ✓ URP pipeline has a valid renderer assigned.");
            }
            else
            {
                Debug.LogError("Blackzone: ✗ URP pipeline has NO renderer! " +
                    "Manually assign '" + rendererData.name + "' in the URP asset inspector.");
            }

            // Check GraphicsSettings
            if (GraphicsSettings.defaultRenderPipeline == urp)
                Debug.Log("Blackzone: ✓ GraphicsSettings.defaultRenderPipeline assigned.");
            else
                Debug.LogWarning("Blackzone: ✗ GraphicsSettings.defaultRenderPipeline not pointing to URP asset.");

            // Check that the assets exist on disk
            if (File.Exists(UrpAssetPath))
                Debug.Log("Blackzone: ✓ URP asset exists at " + UrpAssetPath);
            else
                Debug.LogError("Blackzone: ✗ URP asset NOT found at " + UrpAssetPath);

            if (File.Exists(RendererAssetPath))
                Debug.Log("Blackzone: ✓ Renderer asset exists at " + RendererAssetPath);
            else
                Debug.LogError("Blackzone: ✗ Renderer asset NOT found at " + RendererAssetPath);
        }

        // ---------------------------------------------------------------
        // Helper methods for SerializedObject manipulation
        // ---------------------------------------------------------------

        private static void SetSerializedBool(SerializedObject so, string name, bool value)
        {
            var prop = so.FindProperty(name);
            if (prop != null && prop.propertyType == SerializedPropertyType.Boolean)
                prop.boolValue = value;
        }

        private static void SetSerializedInt(SerializedObject so, string name, int value)
        {
            var prop = so.FindProperty(name);
            if (prop != null && prop.propertyType == SerializedPropertyType.Integer)
                prop.intValue = value;
        }

        private static void SetSerializedFloat(SerializedObject so, string name, float value)
        {
            var prop = so.FindProperty(name);
            if (prop != null && prop.propertyType == SerializedPropertyType.Float)
                prop.floatValue = value;
        }

        // ---------------------------------------------------------------
        // 02 — Android Player Settings
        // ---------------------------------------------------------------

        [MenuItem("Blackzone/02 - Configure Android Player Settings")]
        public static void ConfigureAndroid()
        {
            PlayerSettings.companyName = "Blackzone Studios";
            PlayerSettings.productName = "BLACKZONE";
            PlayerSettings.SetApplicationIdentifier(NamedBuildTarget.Android, "com.blackzone.tactical");
            PlayerSettings.defaultInterfaceOrientation = UIOrientation.LandscapeLeft;

            PlayerSettings.SetScriptingBackend(NamedBuildTarget.Android, ScriptingImplementation.IL2CPP);
            PlayerSettings.SetManagedStrippingLevel(NamedBuildTarget.Android, ManagedStrippingLevel.Low);
            PlayerSettings.Android.targetArchitectures = AndroidArchitecture.ARM64;
            PlayerSettings.Android.minSdkVersion = AndroidSdkVersions.AndroidApiLevel24;
            PlayerSettings.Android.targetSdkVersion = AndroidSdkVersions.AndroidApiLevelAuto;
            PlayerSettings.stripEngineCode = true;
            PlayerSettings.Android.androidTVCompatibility = false;

            PlayerSettings.SplashScreen.show = false;

            EditorUserBuildSettings.SwitchActiveBuildTarget(BuildTargetGroup.Android, BuildTarget.Android);
            EditorUserBuildSettings.androidBuildSystem = AndroidBuildSystem.Gradle;

            AssetDatabase.SaveAssets();
            Debug.Log("Blackzone: Android Player Settings configured (ARM64 / IL2CPP / landscape).");
        }

        // ---------------------------------------------------------------
        // 03 — Weapon + AI Data Assets
        // ---------------------------------------------------------------

        [MenuItem("Blackzone/03 - Create Weapon + AI Data Assets")]
        public static void CreateDataAssets()
        {
            EnsureFolder("Assets/_Blackzone/Resources");
            EnsureFolder(WeaponsResPath);
            EnsureFolder(AiResPath);

            var weapons = WeaponCatalog.GetWeaponDefinitions();
            int weaponCount = 0;
            foreach (var def in weapons)
            {
                string path = WeaponsResPath + "/" + def.weaponId + ".asset";
                if (File.Exists(path)) continue;
                var asset = ScriptableObject.CreateInstance<WeaponDefinition>();
                EditorUtility.CopySerialized(def, asset);
                AssetDatabase.CreateAsset(asset, path);
                weaponCount++;
            }

            var difficulties = AIDifficultyCatalog.GetDifficulties();
            int aiCount = 0;
            foreach (var d in difficulties)
            {
                string path = AiResPath + "/" + d.difficultyId + ".asset";
                if (File.Exists(path)) continue;
                var asset = ScriptableObject.CreateInstance<AIDifficultyDefinition>();
                EditorUtility.CopySerialized(d, asset);
                AssetDatabase.CreateAsset(asset, path);
                aiCount++;
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"Blackzone: created {weaponCount} weapon assets and {aiCount} AI difficulty assets.");
        }

        // ---------------------------------------------------------------
        // Utility
        // ---------------------------------------------------------------

        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            string parent = Path.GetDirectoryName(path).Replace('\\', '/');
            string leaf = Path.GetFileName(path);
            if (!AssetDatabase.IsValidFolder(parent)) EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, leaf);
        }
    }
}
