using System.IO;
using Blackzone.AI;
using Blackzone.Weapons;
using UnityEditor;
using UnityEditor.Build;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

namespace Blackzone.EditorTools
{
    /// <summary>
    /// One-time project setup menus. The runtime game builds itself from code,
    /// so these items only configure editor-level data:
    ///  01 - URP render pipeline asset + quality levels (Low/Medium/High)
    ///  02 - Android Player Settings (ARM64, landscape, IL2CPP, package id)
    ///  03 - ScriptableObject data assets from the code catalogs
    /// ProjectSettings.asset itself is intentionally regenerated by Unity,
    /// never hand-authored (avoids YAML corruption).
    /// </summary>
    public static class BlackzoneProjectSetup
    {
        private const string UrpAssetPath = "Assets/_Blackzone/Settings/URP/BlackzoneURP.asset";
        private const string WeaponsResPath = "Assets/_Blackzone/Resources/Weapons";
        private const string AiResPath = "Assets/_Blackzone/Resources/AI";

        // ---------------------------------------------------------------
        [MenuItem("Blackzone/01 - Create URP Asset + Quality Levels")]
        public static void CreateUrpAndQuality()
        {
            EnsureFolder("Assets/_Blackzone/Settings/URP");

            var urp = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(UrpAssetPath);
            if (urp == null)
            {
                urp = UniversalRenderPipelineAsset.Create();
                AssetDatabase.CreateAsset(urp, UrpAssetPath);
                AssetDatabase.SaveAssets();
                Debug.Log("Blackzone: URP asset created at " + UrpAssetPath);
            }

            GraphicsSettings.defaultRenderPipeline = urp;
            GraphicsSettings.renderPipelineAsset = urp;

            // Ensure at least 3 quality levels and point them at the URP asset.
            if (QualitySettings.names.Length < 3)
                QualitySettings.AddQualityLevel(3 - QualitySettings.names.Length, false);

            for (int i = 0; i < QualitySettings.names.Length; i++)
            {
                QualitySettings.SetQualityLevel(i, false);
                QualitySettings.renderPipeline = urp;
            }

            QualitySettings.vSyncCount = 0;
            AssetDatabase.SaveAssets();
            Debug.Log("Blackzone: quality levels configured with URP asset.");
        }

        // ---------------------------------------------------------------
        [MenuItem("Blackzone/02 - Configure Android Player Settings")]
        public static void ConfigureAndroid()
        {
            PlayerSettings.companyName = "Blackzone Studios";
            PlayerSettings.productName = "BLACKZONE";
            PlayerSettings.SetApplicationIdentifier(NamedBuildTarget.Android, "com.blackzone.tactical");
            PlayerSettings.defaultInterfaceOrientation = UIOrientation.LandscapeLeft;

            PlayerSettings.SetScriptingBackend(NamedBuildTarget.Android, ScriptingImplementation.IL2CPP);
            PlayerSettings.SetManagedStrippingLevel(NamedBuildTarget.Android, ManagedStrippingLevel.Low);
            PlayerSettings.Android.targetArchitectures = AndroidArchitecture.ARM64;
            PlayerSettings.Android.minSdkVersion = AndroidSdkVersions.AndroidApiLevel24;
            PlayerSettings.Android.targetSdkVersion = AndroidSdkVersions.AndroidApiLevelAuto;
            PlayerSettings.stripEngineCode = true;
            PlayerSettings.Android.androidTVCompatibility = false;

            PlayerSettings.SplashScreen.show = false;

            EditorUserBuildSettings.SwitchActiveBuildTarget(BuildTargetGroup.Android, BuildTarget.Android);
            EditorUserBuildSettings.androidBuildSystem = AndroidBuildSystem.Gradle;

            AssetDatabase.SaveAssets();
            Debug.Log("Blackzone: Android Player Settings configured (ARM64 / IL2CPP / landscape).");
        }

        // ---------------------------------------------------------------
        [MenuItem("Blackzone/03 - Create Weapon + AI Data Assets")]
        public static void CreateDataAssets()
        {
            EnsureFolder("Assets/_Blackzone/Resources");
            EnsureFolder(WeaponsResPath);
            EnsureFolder(AiResPath);

            var weapons = WeaponCatalog.GetWeaponDefinitions();
            int weaponCount = 0;
            foreach (var def in weapons)
            {
                string path = WeaponsResPath + "/" + def.weaponId + ".asset";
                if (File.Exists(path)) continue;
                var asset = ScriptableObject.CreateInstance<WeaponDefinition>();
                EditorUtility.CopySerialized(def, asset);
                AssetDatabase.CreateAsset(asset, path);
                weaponCount++;
            }

            var difficulties = AIDifficultyCatalog.GetDifficulties();
            int aiCount = 0;
            foreach (var d in difficulties)
            {
                string path = AiResPath + "/" + d.difficultyId + ".asset";
                if (File.Exists(path)) continue;
                var asset = ScriptableObject.CreateInstance<AIDifficultyDefinition>();
                EditorUtility.CopySerialized(d, asset);
                AssetDatabase.CreateAsset(asset, path);
                aiCount++;
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"Blackzone: created {weaponCount} weapon assets and {aiCount} AI difficulty assets.");
        }

        // ---------------------------------------------------------------
        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            string parent = Path.GetDirectoryName(path).Replace('\\', '/');
            string leaf = Path.GetFileName(path);
            if (!AssetDatabase.IsValidFolder(parent)) EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, leaf);
        }
    }
}
